pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
version: '0.1.{build}'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT)
build_script:
  - cmd: >-
      nuget restore

      msbuild /BinaryLogger /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: >-
      cd Chemo\bin\Release

      Get-ChildItem * -Include *.xml -Recurse | Remove-Item

      Get-ChildItem * -Include *.pdb -Recurse | Remove-Item

      cd ..\..\..\

      7z a ChemoDevBuild.zip .\Chemo\bin\Release\*
      
artifacts:
  - path: ChemoDevBuild.zip
    name: ChemoDevBuild
